name: minibook-frontend
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: UMGC-Capstone-Project/minibook-frontend
  name: minibook-frontend